# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loginsys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('sex', models.CharField(choices=[('Man', 'Чоловік'), ('Woman', 'Жінка')], max_length=20, verbose_name='Стать')),
                ('avatar', models.ImageField(blank=True, help_text='Фото користувача', upload_to=loginsys.models.upload_location, verbose_name='Аватарка')),
                ('profile_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення профіля')),
                ('profile_update', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення профіля')),
            ],
            options={
                'db_table': 'profile',
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
            },
        ),
    ]
