# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 12:54
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=50, verbose_name='Назва статті')),
                ('article_text', models.TextField(max_length=1000, verbose_name='Текст статті')),
                ('article_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('article_update', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('article_likes', models.IntegerField(default=0, verbose_name='Подобається')),
                ('article_image', models.ImageField(blank=True, help_text='Зображення до статті', null=True, upload_to=blog.models.upload_location, verbose_name='Картинки')),
                ('article_slug', models.SlugField(blank=True, unique=True, verbose_name='Ім`я статті транслітом')),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='navigation.Category', verbose_name='Категорія')),
            ],
            options={
                'db_table': 'articles',
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=50, verbose_name='Назва тега')),
                ('tag_name', models.SlugField(verbose_name='Ім`я тега транслітом')),
            ],
            options={
                'db_table': 'tags',
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тегі',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_tag',
            field=models.ManyToManyField(related_name='articles', to='blog.Tag', verbose_name='Тегі'),
        ),
    ]
